### ISSUE TITLE
Termite support

### ISSUE THREAD

**Issue by NuckChorris** [ciembor/4bit#19]
Termite is an up-and-coming terminal developed on VTE, popular amongst Arch Linux and Gentoo users; it's minimalist, and easy to generate for.  Right now I'm just using sed to turn the XFCE config into the right one for this.

Config file is described in https://github.com/thestinger/termite/blob/master/config

**Comment by ciembor** [comment]
Done in https://github.com/ciembor/4bit/commit/cf4b2664295e2b3596e34b95f685cea15b0e3b85
