### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by Calinou** [ciembor/4bit#23]
I can't seem to find the license for this project. Would you add one, please? See http://choosealicense.com/ for more information.

**Comment by ciembor** [comment]
It's MIT with additional Crockford's requirement - "The Software shall be used for Good, not Evil".

**Comment by Calinou** [comment]
> It's MIT with additional Crockford's requirement - "The Software shall be used for Good, not Evil".

Sorry, but this isn't a free license; neither the OSI nor the [FSF](http://www.gnu.org/licenses/license-list#JSON) approve that clause. It adds no value and is very subjective.

**Comment by doggy8088** [comment]
@ciembor Would you please add a `LICENSE` file into your repo?

Ref: [Adding a license to a repository - User Documentation](https://help.github.com/articles/adding-a-license-to-a-repository/)
