### ISSUE TITLE
Get Scheme doesn't work

### ISSUE THREAD

**Issue by jinahya** [ciembor/4bit#26]
From the popped up panel from http://ciembor.github.io/4bit/#
No buttons downloads any file.

**Comment by ciembor** [comment]
It looks it doesn't work in new Chrome, don't know the reason yet. Works in Firefox. @jinahya, do you know how it could be solved and what's the problem?

**Comment by ciembor** [comment]
It works in Chrome when you copy the link from button and paste it in a new tab. Doesn't work when you use data text plain with target="_blank"...

**Comment by ciembor** [comment]
I reported a bug to the Google Chrome, it worked in previous versions and I don't have time to read their changelog to find what could couse the problem.

**Comment by jinahya** [comment]
@ciembor I'm sorry I wish I can help. Even with chrome, all I could do is copy the content, which is newly tabbed, and put it into my `.minttyrc`. Isn't it supposed to download as a file with properly named? Thanks.

**Comment by ciembor** [comment]
No, right now it's opened in a new tab. I'm sorry, but I don't have too much time to maintain this project. I will probably rewrite it in future, but don't know when.

**Comment by ummahusla** [comment]
So half year later on, it's still broken. This is why I don't like open source projects that much.

**Comment by ciembor** [comment]
@ummahusla sorry for that. I can assure you it has nothing to do with open source itself. Actually because it is open source there is higher probability, that it will work sooner, because other people can fix it if they really need this. If you know how to solve the problem I will be really glad if you make a pull request.

**Comment by chrisj-skinner** [comment]
The only browser I can get it working in is Firefox (53.0). So it still works.

**Comment by JerryChin** [comment]
I run into the same problem on Chrome, after turning off `AdBlock`, I'm able to download the nice scheme!

**Comment by ciembor** [comment]
@JerryChin That's really interesting, thanks!

**Comment by ummahusla** [comment]
@JerryChin Lol it actually seems to work when Adblock is disabled in Chrome 🎉🎉🎉

**Comment by tomasjura** [comment]
Firefox 57.0.1 + AddBlock = same issue. 

It seems that Firefox will block the data: url scheme for [certain cases](https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-58/) permanently.  What about inserting generated configuration to clipboard?

**Comment by LMLB** [comment]
I had this problem with AdBlock Plus on Firefox. I fixed it by adding `@@data:text/plain,$popup` to my custom filters.

**Comment by sebma** [comment]
Disabling [uBlockOrigin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) did not solve the problem 😞 

Any idea how to make it work ?

**Comment by ciembor** [comment]
@sebma could you give more info? Browser, version, extensions. You can try to disable all extensions, maybe we will find one that breaks it. I use Brave browser and it works even with ads blocking (integrated in Brave).

**Comment by sebma** [comment]
@ciembor Hi,
> @sebma could you give more info? Browser, version, extensions. You can try to disable all extensions, maybe we will find one that breaks it.

I'm using Firefox ESR v102.10.0 will all addons disabled.

**Comment by sebma** [comment]
@ciembor Hi,
> @sebma temporary solution: right-click on the link (button for your terminal), open in new tab. If it's still empty, but there is some code in your address bar, refresh page. I will dig into the problem, but I have to set up this project localy and it's tricky after 11 years (Google Closure Library and compiler changed a lot over time).

Opening the button with "right-click on the link (button for your terminal), open in new tab" opens an empty tab and refresh on that tab does nothing.

**Comment by ciembor** [comment]
@sebma Fixed, now you can download exported files directly instead of opening in a new tab.

**Comment by sebma** [comment]
@ciembor Great, thanks. You have fixed this in the commit number [7ed5cd1](https://github.com/ciembor/4bit/commit/7ed5cd1c9df2829128971cee2d8110c605820bb5) right ?
