### ISSUE TITLE
Dyeing doesn't get reflected in background color setting

### ISSUE THREAD

**Issue by alinnert** [ciembor/4bit#32]
When I set the background color to `bright_black` and use the `dye` feature it looks like the background color changes its color in the preview. But this is not reflected in the exported settings (tried with `.minttyrc`). For `bright_black` the background color always gets exported as `BackgroundColour=34,34,34`. This is not right, is it?

**Comment by ciembor** [comment]
It looks like it isn't, thanks for noticing it! Unfortunately I don't have time for this project at the moment :(.
