### ISSUE TITLE
Clicking export links does nothing

### ISSUE THREAD

**Issue by CervEdin** [ciembor/4bit#40]
When I click any of the Export scheme to configurations file, nothing happens

I expected a prompt to download the file or the text copied to clipboard but neither happened.

I managed to get around this by using "save link as"

Chrome 88.0.4324.182

**Comment by CodeSwimBikeRunner** [comment]
opens a new blank tab for me.

**Comment by Kamrulhasan12345** [comment]
i figured it out
copy the link and go to js console, type:
```js
decodeURIComponent(URL_HERE)
```
then you will get a clickable link:

![image](https://user-images.githubusercontent.com/32530625/174524672-ab626c15-0fcc-4da6-b340-8048416143d1.png)

after clicking, you will get a fresh page, with necessary things printed:
![image](https://user-images.githubusercontent.com/32530625/174524789-27e9a3b6-c972-4d5f-adc3-a33619b2719b.png)

**Comment by ciembor** [comment]
Yeah, something is definitely wrong, same happens when some ad blocking is enabled, not sure what's the reason. I have to dig into it.

**Comment by ciembor** [comment]
Fixed, now you can download exported files directly instead of opening in a new tab.
