### ISSUE TITLE
Unable to run it on local space. 

### ISSUE THREAD

**Issue by adsingh14** [ciembor/4bit#41]
I followed your guide and changed `APP_PATH`, but it didn't load CSS. Can you please provide a tutorial to run it after cloning ?

**Comment by ciembor** [comment]
I added Google Closure Library as a submodule, so it shouldn't be a problem now. Let me know if works (but yeah, you wrote 2 years ago :)). Dependencies became tricky since it was written and not really maintained since 2012.
