### ISSUE TITLE
The URL in the README.md is wrong

### ISSUE THREAD

**Issue by sebma** [ciembor/4bit#43]
Hi, the URL in the [README.md](../blob/master/README.md) is wrong , it should be : 
https://ciembor.github.io/4bit
instead of : 
https://ciembor.github.com/4bit

**Comment by ciembor** [comment]
Yes, Github change a lot in 10 years ;).

**Comment by sebma** [comment]
@ciembor Thanks. You have to also fix the URL in the "About" section on the top right side of your repository : https://github.com/ciembor/4bit

**Comment by sebma** [comment]
@ciembor Also, in your README.md, the [original colors.sh](http://code.google.com/p/iterm2/source/browse/trunk/tests/colors.sh) has now moved to [original colors.sh](https://github.com/gnachman/iTerm2/blob/master/tests/colors.sh).

**Comment by ciembor** [comment]
I will check all the links, a lot of things change in 11 years ;). Time to take care about is, i'm surprised people still use it.
